// ============================================================
// PROJECT 1: Retail Sales Performance Dashboard
// Dataset  : Sample Superstore (Kaggle)
// Source   : https://www.kaggle.com/datasets/vivek468/superstore-dataset-final
// Author   : Akshay Vinod
// File     : 03_dax_measures.dax
// Desc     : Power BI DAX — KPI cards, MoM, YoY, rankings
// HOW TO USE: In Power BI Desktop → Modeling tab → New Measure
//             Paste each block below as a separate measure
// ============================================================

// ── BASE MEASURES ────────────────────────────────────────────

Total Revenue =
    SUM(fact_sales[sales])

Total Profit =
    SUM(fact_sales[profit])

Total Orders =
    DISTINCTCOUNT(fact_sales[order_id])

Unique Customers =
    DISTINCTCOUNT(fact_sales[customer_id])

Units Sold =
    SUM(fact_sales[quantity])

Avg Order Value =
    DIVIDE([Total Revenue], [Total Orders], 0)

Profit Margin % =
    DIVIDE([Total Profit], [Total Revenue], 0) * 100

Avg Discount % =
    AVERAGE(fact_sales[discount]) * 100

// ── TIME INTELLIGENCE — MoM ──────────────────────────────────

Revenue Last Month =
    CALCULATE(
        [Total Revenue],
        DATEADD(dim_date[date_key], -1, MONTH)
    )

MoM Revenue Growth % =
    VAR curr = [Total Revenue]
    VAR prev = [Revenue Last Month]
    RETURN
        IF(ISBLANK(prev), BLANK(),
           DIVIDE(curr - prev, prev, 0) * 100)

MoM Arrow =
    IF([MoM Revenue Growth %] >= 0, "▲ ", "▼ ")
        & FORMAT(ABS([MoM Revenue Growth %]), "0.0") & "%"

// ── TIME INTELLIGENCE — YoY ──────────────────────────────────

Revenue Prior Year =
    CALCULATE(
        [Total Revenue],
        SAMEPERIODLASTYEAR(dim_date[date_key])
    )

YoY Revenue Growth % =
    DIVIDE([Total Revenue] - [Revenue Prior Year],
           [Revenue Prior Year], 0) * 100

Profit Prior Year =
    CALCULATE(
        [Total Profit],
        SAMEPERIODLASTYEAR(dim_date[date_key])
    )

YoY Profit Growth % =
    DIVIDE([Total Profit] - [Profit Prior Year],
           [Profit Prior Year], 0) * 100

// ── YTD TOTALS ────────────────────────────────────────────────

Revenue YTD =
    TOTALYTD([Total Revenue], dim_date[date_key])

Profit YTD =
    TOTALYTD([Total Profit], dim_date[date_key])

Revenue YTD Prior Year =
    CALCULATE(
        [Revenue YTD],
        SAMEPERIODLASTYEAR(dim_date[date_key])
    )

// ── RANKING & DRILL-THROUGH ───────────────────────────────────

Sub-Category Revenue Rank =
    RANKX(
        ALL(fact_sales[sub_category]),
        [Total Revenue], , ASC, DENSE
    )

Is Bottom 3 Flag =
    IF([Sub-Category Revenue Rank] <= 3, "⚠ Underperforming", "Normal")

Category Revenue Rank =
    RANKX(
        ALL(fact_sales[category]),
        [Total Revenue], , DESC, DENSE
    )

// ── KPI CARD LABELS ──────────────────────────────────────────

Revenue Label =
    "$" & FORMAT([Total Revenue] / 1000000, "#,##0.00") & "M"

Profit Margin Label =
    FORMAT([Profit Margin %], "0.0") & "%"

Orders Label =
    FORMAT([Total Orders], "#,##0") & " orders"

// ── CUSTOMER ANALYSIS ────────────────────────────────────────

Revenue per Customer =
    DIVIDE([Total Revenue], [Unique Customers], 0)

Profit per Customer =
    DIVIDE([Total Profit], [Unique Customers], 0)
